# This file was generated by GoReleaser. DO NOT EDIT.
cask "kli" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/kli"]
    end
  end

  version "0.3.777"

  on_macos do
    on_arm do
      sha256 "a507707640b33b3114f666ed4e4afc44db9df2f08bed94192b3ca5ca9c37d0a5"
      url "https://github.com/dsx-ai-factory/workload-map/releases/download/v#{version}/karta_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ceedaf431f544929bc48f261183b946ae6bb17f7f5f10b9b3046cda138be54af"
      url "https://github.com/dsx-ai-factory/workload-map/releases/download/v#{version}/karta_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "24078f8d98dcb81b5ace66f3431e661c3a8029496774836bdaff1da26183c5f2"
      url "https://github.com/dsx-ai-factory/workload-map/releases/download/v#{version}/karta_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4c617df1f08068472e9f6e45a90ffc06f09d1d6cb6d6c2fd3336c1ae0cb7b4e5"
      url "https://github.com/dsx-ai-factory/workload-map/releases/download/v#{version}/karta_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kli"
  desc "Workload-aware visibility for any Kubernetes workload type"
  homepage "https://github.com/dsx-ai-factory/workload-map"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kli"

  # No zap stanza required
end
