# This file was generated by GoReleaser. DO NOT EDIT.
cask "kli" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/kli"]
    end
  end

  version "0.4.100"

  on_macos do
    on_arm do
      sha256 "298415d402c831883babf30b355de13d15152f8ff8350412001148dcfd0aa642"
      url "https://github.com/AviadHayumi/workload-map/releases/download/v#{version}/karta_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5d1caad2d4fc95acd1b16995856e1f256cee28ff4a6239b42cdf5dba6f282187"
      url "https://github.com/AviadHayumi/workload-map/releases/download/v#{version}/karta_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1dc1b580dbdc194984c45e82501d966ccf5ec133914a9265dda0a4c2e6b40138"
      url "https://github.com/AviadHayumi/workload-map/releases/download/v#{version}/karta_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4a9d7123df67e2f93446cd259b4d2c5cde1c4dd5f0c83fec89eac9105a20226c"
      url "https://github.com/AviadHayumi/workload-map/releases/download/v#{version}/karta_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kli"
  desc "Workload-aware visibility for any Kubernetes workload type"
  homepage "https://github.com/AviadHayumi/workload-map"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kli"

  # No zap stanza required
end
